### ISSUE TITLE
npm install pulls in > 70 modules

### ISSUE THREAD

**Issue by nchen63** [yeoman/update-notifier#101]
I expected this to be more lightweight, but it pulls in 74 modules and adds 60 modules to our project. Can this be pared down?

```
 update-notifier@1.0.3
  ├─┬ boxen@0.6.0
  │ ├── ansi-align@1.1.0
  │ ├── camelcase@2.1.1
  │ ├── cli-boxes@1.0.0
  │ ├── filled-array@1.1.0
  │ ├── object-assign@4.1.1
  │ ├─┬ repeating@2.0.1
  │ │ └─┬ is-finite@1.0.2
  │ │   └── number-is-nan@1.0.1
  │ ├─┬ string-width@1.0.2
  │ │ ├── code-point-at@1.1.0
  │ │ └── is-fullwidth-code-point@1.0.0
  │ └── widest-line@1.0.0
  ├─┬ chalk@1.1.3
  │ ├── ansi-styles@2.2.1
  │ ├── escape-string-regexp@1.0.5
  │ ├─┬ has-ansi@2.0.0
  │ │ └── ansi-regex@2.1.1
  │ ├── strip-ansi@3.0.1
  │ └── supports-color@2.0.0
  ├─┬ configstore@2.1.0
  │ ├─┬ dot-prop@3.0.0
  │ │ └── is-obj@1.0.1
  │ ├── graceful-fs@4.1.11
  │ ├─┬ mkdirp@0.5.1
  │ │ └── minimist@0.0.8
  │ ├── os-tmpdir@1.0.2
  │ ├── osenv@0.1.4
  │ ├── uuid@2.0.3
  │ └─┬ write-file-atomic@1.3.1
  │   ├── imurmurhash@0.1.4
  │   └── slide@1.1.6
  ├── is-npm@1.0.0
  ├─┬ latest-version@2.0.0
  │ └─┬ package-json@2.4.0
  │   ├─┬ got@5.7.1
  │   │ ├─┬ create-error-class@3.0.2
  │   │ │ └── capture-stack-trace@1.0.0
  │   │ ├── duplexer2@0.1.4
  │   │ ├── is-redirect@1.0.0
  │   │ ├── is-retry-allowed@1.1.0
  │   │ ├── is-stream@1.1.0
  │   │ ├── lowercase-keys@1.0.0
  │   │ ├── node-status-codes@1.0.0
  │   │ ├─┬ parse-json@2.2.0
  │   │ │ └─┬ error-ex@1.3.0
  │   │ │   └── is-arrayish@0.2.1
  │   │ ├─┬ pinkie-promise@2.0.1
  │   │ │ └── pinkie@2.0.4
  │   │ ├── read-all-stream@3.1.0
  │   │ ├─┬ readable-stream@2.2.2
  │   │ │ ├── buffer-shims@1.0.0
  │   │ │ ├── core-util-is@1.0.2
  │   │ │ ├── inherits@2.0.3
  │   │ │ ├── isarray@1.0.0
  │   │ │ ├── process-nextick-args@1.0.7
  │   │ │ ├── string_decoder@0.10.31
  │   │ │ └── util-deprecate@1.0.2
  │   │ ├── timed-out@3.1.3
  │   │ ├── unzip-response@1.0.2
  │   │ └─┬ url-parse-lax@1.0.0
  │   │   └── prepend-http@1.0.4
  │   ├─┬ registry-auth-token@3.1.0
  │   │ └─┬ rc@1.1.6
  │   │   ├── deep-extend@0.4.1
  │   │   ├── ini@1.3.4
  │   │   ├── minimist@1.2.0
  │   │   └── strip-json-comments@1.0.4
  │   └── registry-url@3.1.0
  ├── lazy-req@1.1.0
  ├─┬ semver-diff@2.1.0
  │ └── semver@5.3.0
  └─┬ xdg-basedir@2.0.0
    └── os-homedir@1.0.2
```

**Comment by wtgtybhertgeghgtwtg** [comment]
For the most part, it's just because some of these packages (`boxen`, `configstore`, `latest-version`, `package-json`, `xdg-basedir`, et cetera) haven't updating in a while.  I'm working on bumping the minimum supported `node` version to `node>=4`, so that should help.

**Comment by sindresorhus** [comment]
You're not realizing how many things `update-notifier` does and how well it does it. It takes a lot of code to make things perfect on the brokenness we build on (computers). Pretty much every dependency in that list has a reason for being there. From the difficulty of correctly communicating with a remote server to presenting the update notification in the terminal with colors in a cross-platform manner, saving the update to disk, etc. Many of these dependencies are popular too, so they will be deduped if you use many other dependencies. In the end, dependencies are cheap with npm. Most of these dependencies are also tiny. If it's a problem for you, you could always [bundle them](https://github.com/sheerun/npm-packer).

**Comment by sindresorhus** [comment]
@wtgtybhertgeghgtwtg Yes, I've already done that today. Check the commits here ;)

**Comment by wtgtybhertgeghgtwtg** [comment]
Sorry, sorry.
Side note: you actually did solve the issue, since it not longer takes in >70 modules.  It takes in exactly 70.
