### ISSUE TITLE
Docker build: Error: EACCES: permission denied

### ISSUE THREAD

**Issue by BorntraegerMarc** [yeoman/update-notifier#109]
Original issue: https://github.com/remy/nodemon/issues/1014

When I run my NodeJS app in a docker container (which uses nodemon) I get the following error:
```
/home/app/node_modules/mkdirp/index.js:90

Error: EACCES: permission denied, mkdir '/home/app/.config'
komed-app      |     at Error (native)
komed-app      |     at Object.fs.mkdirSync (fs.js:922:18)
komed-app      |     at sync (/home/app/node_modules/mkdirp/index.js:71:13)
komed-app      |     at Function.sync (/home/app/node_modules/mkdirp/index.js:77:24)
komed-app      |     at Object.get (/home/app/node_modules/nodemon/node_modules/configstore/index.js:38:13)
komed-app      |     at Object.Configstore (/home/app/node_modules/nodemon/node_modules/configstore/index.js:27:44)
komed-app      |     at new UpdateNotifier (/home/app/node_modules/nodemon/node_modules/update-notifier/index.js:34:17)
komed-app      |     at module.exports (/home/app/node_modules/nodemon/node_modules/update-notifier/index.js:123:23)
komed-app      |     at Object.<anonymous> (/home/app/node_modules/nodemon/bin/nodemon.js:15:27)
komed-app      |     at Module._compile (module.js:570:32)
```

My Dockerfile:
```
FROM node:6.9.2-alpine

RUN addgroup -g 997 -S app \
&& adduser -G app -u 998 -D -S app

ENV HOME=/home/app

RUN mkdir -p $HOME \
&& mkdir -p $HOME/.config
RUN chown -R app:app $HOME

USER app
WORKDIR $HOME/

VOLUME ["/home/app/uploads"]

EXPOSE 8000

CMD [ "npm", "run", "start" ]
```
The weird thing is that I already execute `chown -R app:app` in my build... Any ideas?

I tried to change the write perms but it seems not to take any effect when launching nodemon.
See the line `RUN chown -R app:app $HOME` in my Dockerfile. This should take care of the permissions but seems to take no effect... Or am I missing something?

I only get the error on Linux (ubuntu)! Not even OSX...

**Comment by SBoudrias** [comment]
What are you running exactly? `docker run {...?}`

Are you mapping a user id like `-u $(id -u):$(id -g)`?

But for further support you should check the Docker community. This is not an update-notifier bug, it's just a permission issue due to wrong settings.

**Comment by BorntraegerMarc** [comment]
@SBoudrias Thanks for your fast reply, but I somehow doubt it's in the project setup. Because it works fine with other OS's as well...

Anyway: you can see in my Dockerfile that I execute `USER app` so with that command the docker container gets run as the user app. I then only execute `docker-compose up` from my CMD...

This usually works with all my other libraries fine.
