### ISSUE TITLE
npm is suggested when installed via yarn (global install only)

### ISSUE THREAD

**Issue by OmgImAlexis** [yeoman/update-notifier#118]
I have xo installed via yarn not npm which means if I "update" with npm I'll end up with two copies of xo in my `$PATH`.

```
➜  SickRage git:(develop) ✗ realpath $(which xo)      
/Users/xo/.config/yarn/global/node_modules/xo/cli.js
```

```
   ╭───────────────────────────────────────╮
   │                                       │
   │   Update available 0.17.1 → 0.18.2    │
   │       Run npm i -g xo to update       │
   │                                       │
   ╰───────────────────────────────────────╯
```

**Comment by sindresorhus** [comment]
Yarn users should IMHO know what to do when they see `npm install` instructions. Same with readmes, almost no projects document Yarn in the install instructions.

**Comment by OmgImAlexis** [comment]
Is there any harm in adding a check for it? Just checking if the path to the package contains yarn should be enough to determine if it's installed via yarn.

**Comment by SBoudrias** [comment]
@OmgImAlexis That's a good idea. I'm sure a PR is welcomed to fix that.

**Comment by LitoMore** [comment]
```javascript
const updateNotifier = require('update-notifier');
const pkg = require('chalk/package');

const notifier = updateNotifier({pkg});

notifier.notify();
```

How to determine whether `chalk` is installed by `npm` or `yarn`?

**Comment by LitoMore** [comment]
I will make a pull request to solve the issue recently.
