### ISSUE TITLE
Import through webpack fails on import-lazy

### ISSUE THREAD

**Issue by julianxhokaxhiu** [yeoman/update-notifier#123]
HI,

I am trying to use this module through webpack, and I am having some deep issues with `import-lazy` package, which seems not to be webpack friendly as well.

To make it short, I found a way to fix the build issue by using the solution mentioned here ( https://github.com/webpack/webpack/issues/4596#issuecomment-304441388 ) although it seems is not enough to make my application running on top of this package.

This is an excerpt of the error I get during runtime of my application once it is bundled with WebPack:
```
/path/to/project/dist/webpack:/node_modules/update-notifier ^\.\/.*$:16
                throw new Error("Cannot find module '" + req + "'.");
^
Error: Cannot find module 'chalk'.
    at webpackContextResolve (/path/to/project/dist/webpack:/node_modules/update-notifier ^\.\/.*$:16:1)
    at webpackContext (/path/to/project/dist/webpack:/node_modules/update-notifier ^\.\/.*$:11:1)
    at lazy (/path/to/project/dist/webpack:/node_modules/import-lazy/index.js:2:1)
    at /path/to/project/dist/webpack:/node_modules/import-lazy/index.js:10:1
    at new UpdateNotifier (/path/to/project/dist/webpack:/node_modules/update-notifier/index.js:55:1)
    at module.exports.options (/path/to/project/dist/webpack:/node_modules/update-notifier/index.js:145:1)
    at Object.__webpack_exports__.default (/path/to/project/dist/webpack:/src/index.js:31:1)
    at Object.<anonymous> (/path/to/project/bin/cli.js:5:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

In my opinion there are three ways to fix it:
1) Just remove `import-lazy` and make use of the normal require ( to make it webpack friendly )
2) Publish a new package with `-webpack` suffix, but this will create maintenance overhead on your side
3) Detect if the module is being bundled with webpack, and if yes, make sure of the normal require ( not sure if it will work 100% )

Any help from your side is really appreciated. Feel free to approach me if any question arise.

Thank you and best regards,
Julian

**Comment by sindresorhus** [comment]
Use the Webpack issue tracker for Webpack related issues. This module works in the Node.js ecosystem, and it's up to Webpack to be compatible with it, not the other way around.

**Comment by julianxhokaxhiu** [comment]
Looking at the source code I got a forth option, which would simplify the whole thing:

just create a new js file that is webpack friendly, and we can import that, something like:

```
import updateNotifier from 'update-notifier/webpack'
```

What do you think?

**Comment by cxsper** [comment]
I created a fork for that matter because it seems like it will be never supported

https://github.com/datacrafts-io/update-notifier-webpack
https://www.npmjs.com/package/update-notifier-webpack

Sorry for necro-bumping
