### ISSUE TITLE
update-notifier using old boxen which hangs on some machines

### ISSUE THREAD

**Issue by dankegel** [yeoman/update-notifier#125]
When run in background (or, more precisely, with stderr redirected to a unix domain socket),
'npm install' hangs for me on mac os x 10.11.  This is relatively recent behavior; it affects
npm 5.3.0, but not npm 3.10.8.  I can work around it with 'npm install -g npm@3.10.8'.

The culprit appears to be the older version of boxen required by package.json, i.e. 1.0.0:
https://github.com/yeoman/update-notifier/blob/master/package.json#L36

More recent boxen require more recent versions of term-size, which avoid the hang.

See also https://github.com/npm/npm/issues/18759

**Comment by SBoudrias** [comment]
Mind sending a PR?

**Comment by sindresorhus** [comment]
We target `^1.0.0` which matches the latest version of Boxen, `1.2.1`, so bumping the version is pretty moot. But I'll bump the version since I'm gonna do a new version today anyway.
