### ISSUE TITLE
Simply running npm i update-notifer fails

### ISSUE THREAD

**Issue by githubsaturn** [yeoman/update-notifier#131]
All dependent packages are broken due to this issue.

For example, see:
https://github.com/githubsaturn/captainduckduck/issues/103
and
https://github.com/firebase/firebase-tools/issues/591

**Comment by SBoudrias** [comment]
Not sure what's happening, but this seems to be deeper than update-notifier...

Looks like `timed-out` package isn't found on npm anymore https://www.npmjs.com/package/timed-out (but it still shows on the search? So could it be an issue with npm?)

**Comment by SBoudrias** [comment]
Actually yeah, npm is having issues: https://status.npmjs.org/ (package disappeared)

I'll close this issue as not actionnable from our end.
