### ISSUE TITLE
License for v. 1.0.3 

### ISSUE THREAD

**Issue by spectejb** [yeoman/update-notifier#145]
I receive the 404 page when trying to review the license for v1.0.3.  Could you please add the BSD 2 license file to that version?  Thank you, in advance, for your help!

**Comment by sindresorhus** [comment]
npm used to have a bug where it didn't correctly include license files in packages. We don't maintain older major versions, but upgrade to the latest version and you'll get a correct license file included in the package.

**Comment by spectejb** [comment]
Thanks!  Should we assume that the older versions are also MIT?
