### ISSUE TITLE
Add support for dist-tag versions

### ISSUE THREAD

**Issue by LitoMore** [yeoman/update-notifier#150]
Currently, `update-notifier` only support detect the latest version of the package.

The related code is here: https://github.com/yeoman/update-notifier/blob/master/index.js#L102

For [latest-version@4.0.0](https://github.com/sindresorhus/latest-version), it already supports dist-tag versions. But it will be a breaking change because [latest-version@4.0.0](https://github.com/sindresorhus/latest-version) requires Node.js v6 or later.

I think the API can be designed like this:

Add a `distTag` option and default to `latest`.

```javascript
const updateNotifier = require('update-notifier');
const pkg = require('./package.json');

const notifier = updateNotifier({pkg, distTag: 'beta'});

notifier.notify();
```

**Comment by sindresorhus** [comment]
Sure. The proposed API looks good. PR welcome.
