### ISSUE TITLE
Fewer dependencies

### ISSUE THREAD

**Issue by fabiospampinato** [yeoman/update-notifier#159]
I'm using `update-notifier` in all my CLI apps and I'd like to help make it much smaller and faster.

IMHO especially for CLI apps having a good startup time is critical, and that can be minimized by loading fewer and smaller files from disk. 

Installing `update-notifier` adds 2.4MB on disk for me, that sounds like a lot, I think ideally the whole thing should be <100KB, and _maybe_ it should be bundled into a single file for minimizing FS operations.

Running `npm list` to display the dependency tree shows the following for `update-notifier`:

```
└─┬ update-notifier@3.0.0
  ├─┬ boxen@3.2.0
  │ ├─┬ ansi-align@3.0.0
  │ │ └── string-width@3.1.0 deduped
  │ ├── camelcase@5.3.1
  │ ├── chalk@2.4.2 deduped
  │ ├── cli-boxes@2.2.0
  │ ├─┬ string-width@3.1.0
  │ │ ├── emoji-regex@7.0.3
  │ │ ├── is-fullwidth-code-point@2.0.0
  │ │ └─┬ strip-ansi@5.2.0
  │ │   └── ansi-regex@4.1.0
  │ ├─┬ term-size@1.2.0
  │ │ └─┬ execa@0.7.0
  │ │   ├─┬ cross-spawn@5.1.0
  │ │   │ ├─┬ lru-cache@4.1.5
  │ │   │ │ ├── pseudomap@1.0.2
  │ │   │ │ └── yallist@2.1.2
  │ │   │ ├─┬ shebang-command@1.2.0
  │ │   │ │ └── shebang-regex@1.0.0
  │ │   │ └─┬ which@1.3.1
  │ │   │   └── isexe@2.0.0
  │ │   ├── get-stream@3.0.0
  │ │   ├── is-stream@1.1.0
  │ │   ├─┬ npm-run-path@2.0.2
  │ │   │ └── path-key@2.0.1
  │ │   ├── p-finally@1.0.0
  │ │   ├── signal-exit@3.0.2 deduped
  │ │   └── strip-eof@1.0.0
  │ ├── type-fest@0.3.1
  │ └─┬ widest-line@2.0.1
  │   └── string-width@2.1.1 extraneous
  ├─┬ chalk@2.4.2
  │ ├─┬ ansi-styles@3.2.1
  │ │ └─┬ color-convert@1.9.3
  │ │   └── color-name@1.1.3
  │ ├── escape-string-regexp@1.0.5
  │ └─┬ supports-color@5.5.0
  │   └── has-flag@3.0.0
  ├─┬ configstore@4.0.0
  │ ├─┬ dot-prop@4.2.0
  │ │ └── is-obj@1.0.1
  │ ├── graceful-fs@4.1.15
  │ ├─┬ make-dir@1.3.0
  │ │ └── pify@3.0.0
  │ ├─┬ unique-string@1.0.0
  │ │ └── crypto-random-string@1.0.0
  │ ├─┬ write-file-atomic@2.4.2
  │ │ ├── graceful-fs@4.1.15 deduped
  │ │ ├── imurmurhash@0.1.4
  │ │ └── signal-exit@3.0.2
  │ └── xdg-basedir@3.0.0 deduped
  ├── has-yarn@2.1.0
  ├── import-lazy@2.1.0
  ├─┬ is-ci@2.0.0
  │ └── ci-info@2.0.0
  ├─┬ is-installed-globally@0.1.0
  │ ├─┬ global-dirs@0.1.1
  │ │ └── ini@1.3.5
  │ └─┬ is-path-inside@1.0.1
  │   └── path-is-inside@1.0.2
  ├── is-npm@3.0.0
  ├── is-yarn-global@0.3.0
  ├─┬ latest-version@5.1.0
  │ └─┬ package-json@6.3.0
  │   ├─┬ got@9.6.0
  │   │ ├── @sindresorhus/is@0.14.0
  │   │ ├─┬ @szmarczak/http-timer@1.1.2
  │   │ │ └── defer-to-connect@1.0.2
  │   │ ├─┬ cacheable-request@6.0.0
  │   │ │ ├─┬ clone-response@1.0.2
  │   │ │ │ └── mimic-response@1.0.1 deduped
  │   │ │ ├── get-stream@4.1.0 extraneous
  │   │ │ ├── http-cache-semantics@4.0.3
  │   │ │ ├─┬ keyv@3.1.0
  │   │ │ │ └── json-buffer@3.0.0
  │   │ │ ├── lowercase-keys@1.0.1 deduped
  │   │ │ ├── normalize-url@3.3.0
  │   │ │ └─┬ responselike@1.0.2
  │   │ │   └── lowercase-keys@1.0.1 deduped
  │   │ ├─┬ decompress-response@3.3.0
  │   │ │ └── mimic-response@1.0.1 deduped
  │   │ ├── duplexer3@0.1.4
  │   │ ├── get-stream@4.1.0 extraneous
  │   │ ├── lowercase-keys@1.0.1
  │   │ ├── mimic-response@1.0.1
  │   │ ├── p-cancelable@1.1.0
  │   │ ├── to-readable-stream@1.0.0
  │   │ └─┬ url-parse-lax@3.0.0
  │   │   └── prepend-http@2.0.0
  │   ├─┬ registry-auth-token@3.4.0
  │   │ ├─┬ rc@1.2.8
  │   │ │ ├── deep-extend@0.6.0
  │   │ │ ├── ini@1.3.5 deduped
  │   │ │ ├── minimist@1.2.0
  │   │ │ └── strip-json-comments@2.0.1
  │   │ └── safe-buffer@5.1.2
  │   ├─┬ registry-url@5.1.0
  │   │ └── rc@1.2.8 deduped
  │   └── semver@5.7.0 deduped
  ├─┬ semver-diff@2.1.0
  │ └── semver@5.7.0
  └── xdg-basedir@3.0.0
```

Here there are a few ideas on how to have fewer dependencies, maybe they aren't all applicable to `update-notifier`, but I'd be also interested in making a `update-notifier-core` or something which could then be used by this package and by an hypothetical `update-notifier-slim` package:

- Remove `boxen`: while displaying the box is cool perhaps a slimmer version of this package could just display the message in a regular line. Perhaps we could do without coloring too.
- Remove `string-width`: if we limit ourselves to ASCII characters I suppose we might not need this.
- Remove `import-lazy`: maybe we could just call `require` dynamically when loading the most expensive dependencies.
- Remove `term-size`: maybe the scenarios where it's more reliable then just doing `process.stdout.columns || 80` don't really matter for when `update-notifier` displays the update message?
- Remove `latest-version`: the latest version could be retrieved just by query NPM at e.g. `https://registry.npmjs.org/chalk/latest`. Maybe `latest-version` handles things like pre-releases, private registries etc. though?.

I'll update the list if I can think of something else.

What do you guys think? Are PRs welcome for this?

**Comment by sindresorhus** [comment]
> Installing update-notifier adds 2.4MB on disk for me, that sounds like a lot, I think ideally the whole thing should be <100KB, and maybe it should be bundled into a single file for minimizing FS operations.

While, I'm sure `update-notifier` could be somewhat reduced in size, I don't see it ever being less than 100 KB unless it's bundled into one file. Update notification is more complex than you think. There's a lot of moving pieces when you deal with the network.

> but I'd be also interested in making a update-notifier-core or something which could then be used by this package and by an hypothetical update-notifier-slim package:

I have considered refactoring the update checking mechanism into a separate module without the presentation layer. That way you could choose how to present it yourself by using that module directly. However, I think bundling would give better gains with much less work.

> Remove boxen: while displaying the box is cool perhaps a slimmer version of this package could just display the message in a regular line. Perhaps we could do without coloring too.

That sounds like a completely different package. A lot of people use this because it not only works well, but also looks good.

> Remove string-width: if we limit ourselves to ASCII characters I suppose we might not need this.

We cannot make that assumption. Lots of people use emojis these days.

> Remove import-lazy: maybe we could just call require dynamically when loading the most expensive dependencies.

The JS itself is like [400 bytes](https://bundlephobia.com/result?p=import-lazy@4.0.0). Not worth the effort.

> Remove term-size: maybe the scenarios where it's more reliable then just doing process.stdout.columns || 80 don't really matter for when update-notifier displays the update message?

This is a dependency of `boxen` and outside the control of `update-notifier`. If you really want it removed, you should rather open an issue on Node.js requesting `columns` to work in non-TTY context too.

> Maybe latest-version handles things like pre-releases, private registries etc. though?.

Yes, it does.

**Comment by sindresorhus** [comment]
Can you try https://github.com/zeit/ncc and see what kind of savings it would give?

**Comment by fabiospampinato** [comment]
> One saving, could be to refactor https://github.com/sindresorhus/term-size/blob/master/index.js to not use execa. It can now just use the native childProcess and util.promisify. PR welcome.

I'll look into that 👍 

Do you think it would also be possible to use Node's `http` module instead of `got` in `package-json`?

> Can you try https://github.com/zeit/ncc and see what kind of savings it would give?

The code requires some modification because the way `lazy-import` is used isn't webpack-friendly (https://github.com/sindresorhus/import-lazy/issues/15), but after the code has been adapted I've bundled this:

```js
const notifier = require ( 'update-notifier' );
console.log ( notifier );
```

using this:

```js
require('@zeit/ncc')('./example.js', {
  cache: false,
  externals: [],
  minify: true,
  sourceMap: false,
}).then(({ code, map, assets }) => {
  require ( 'fs' ).writeFileSync ( './dist.js', code );
})
```

and the bundled file weighs just 185kb, which sounds like a big improvement to me.

Just to gather some more numbers I've replaced `boxen`'s usage of `term-size` with just the number `80` and the size went down to 156KB, I guess removing `execa` from `term-size` would bring pretty much the same gains. When removing also `got` from `package-json` the size comes down to 104KB. At that point there will probably be a way to bring the size below 100KB, but I think most performance gains would have been achieved already. Also when disabling minification the size of the bundle roughly doubles.

I'd like to work on the following 3 PRs if that's ok with you:

- Remove `exaca` from `term-size`
- Remove `got` from `package-json`
- Bundle `update-notifier` with `@zeit/ncc`

**Comment by sindresorhus** [comment]
> Do you think it would also be possible to use Node's http module instead of got in package-json?

No, `http` is not usable as a HTTP client in the real world. It's missing way too much. There's a reason Got exists and that it is as big as it is.

> Remove execa from term-size

👍 

> Remove got from package-json

👎 Sorry, this is never going to happen, for the above reasons.

> Bundle update-notifier with @zeit/ncc

I'm still not totally convinced about this. You're trading a small space saving, which is honestly negligible today, with other problems that comes with bundling. With one file, we can not easily do lazy loading, so the startup performance and memory usage might actually be worse, and users will not receive patches from dependencies unless we do a release of `update-notifier`, which might delay critical fixes, and goes against the whole idea of npm.

**Comment by fabiospampinato** [comment]
> You're trading a small space saving, which is honestly negligible today, with other problems that comes with bundling.

It's more about startup performance for me personally.

> With one file, we can not easily do lazy loading, so the startup performance and memory usage might actually be worse

I'll take some measurements about that and report back 👍 But I think in modern engines unless a function is actually executed it doesn't get fully parsed, but just checked for syntax errors or something, which should be a much faster operation, so having to read/check those extra modules shouldn't be as expensive as actually requiring and using them.

> and users will not receive patches from dependencies unless we do a release of update-notifier, which might delay critical fixes, and goes against the whole idea of npm.

Good point 🤔

Another issue with bundling is that some dependencies might get duplicated if the CLI app itself uses any of the dependencies used by `update-notifier`.

It looks like the best option for me might be to bundle the CLI apps themselves, but right now I would have to fork `update-notifier` to make it webpack-compatible, as it's use of `import-lazy` is too dynamic for webpack. This issue gets amplified if multiple dependencies of the CLI app also use `import-lazy` the same way. Should I submit a PR for making `import-lazy` webpack-compatible in `update-notifier`? I would propose making this change across all your packages, but that might be too much work for me (unless it can be mostly automated 🤔) for too little benefits, and writing `importLazy(() => require ( 'foo' ))` would be kind of ugly.

**Comment by fabiospampinato** [comment]
> I'll take some measurements about that and report back 👍

The following code:

```js
const getMemory = () => process.memoryUsage().heapUsed;
const logMemory = () => console.log ( `Memory: ${getMemory ()}b` );

logMemory ();

console.time ( 'require' );
const updateNotifier = require ( 'update-notifier' );
console.timeEnd ( 'require' );

logMemory ();

console.time('notify');
const options = {
  pkg: {
    name: 'public-ip',
    version: '0.9.2'
  },
  updateCheckInterval: 0
};
const updater = updateNotifier(options).notify();
console.timeEnd('notify');

logMemory ();

console.log ( updater.update );
```

Produces the following output when unbundled:

```
Memory: 4331064b
require: 6.117ms
Memory: 4467280b
notify: 0.528ms
Memory: 4489224b
```

And the following output when bundled:

```
Memory: 5572264b
require: 4.738ms
Memory: 5845488b
notify: 0.590ms
Memory: 5867392b
undefined
```

From these numbers I'm taking that:

- The startup time doesn't seem to be a problem at all.
- Bundling the code increases the memory consumption considerably (~25%), albeit "considerably" in this trivial sample code that doesn't do much. The reason for this is that I think `got` and `execa` are actually imported only on the separate process when unbundled, while when bundling the main process has to read their code too.

A few things to note:

- I've tried running the unbundled version of that code multiple times and I'm always getting `updater.update === undefined`, I've no idea why.
- Since `got` and `execa`, which I think are probably the most expensive dependencies to import in this dependency tree, are only required in the separate process this little "benchmark" isn't actually useful for measuring the time it takes to require them.
- Since this package relies on a separate "check.js" file I don't think CLI apps that are using `update-notifier` can be bundled at all 🤔

I'd like `update-notifier` to be usable in bundled apps, so either:

- It's possible to write it so that it uses a single process: but I guess this might be a problem because we want CLI apps to start and exit quickly, and we might not have the time for waiting for the network request to complete 🤔 

- It's possible to write it so that webpack bundles it properly: I guess hypothetically `check.js` could be itself bundled, hard coded into `index.js` as a string, written somewhere on disk on startup and then executed in another process, but that sounds a bit crazy to me. Maybe there's a saner solution.

What do you suggest? Maybe having `update-notifier` bundle-able with webpack isn't worth it?

**Comment by sindresorhus** [comment]
> Should I submit a PR for making update-notifier's usage of import-lazy webpack-compatible?

Every time I hear people requesting some Node.js module to be "Webpack compatible", I think how it would be better for Webpack to be compatible with the ecosystem it's intruding on instead. Instead of every module having to change because of Webpack, it would be better to put all that energy into finding solution in Webpack itself, which would benefit the whole ecosystem.

> I would propose making this change across all your packages

Definitely not interested in that.

> I've tried running the unbundled version of that code multiple times and I'm always getting updater.update === undefined, I've no idea why.

Because it only notifies about an update once a day. You have to reset the config. See how to test it here: https://github.com/yeoman/update-notifier/blob/master/example.js

> Since got and execa, which I think are probably the most expensive dependencies to import in this dependency tree, are only required in the separate process this little "benchmark" isn't actually useful for measuring the time it takes to require them.

But since they're not imported in the main process, a benchmark wouldn't be useful regardless.

> Since this package relies on a separate "check.js" file I don't think CLI apps that are using update-notifier can be bundled at all 🤔

Again, this is a problem for Webpack to solve, not for every single module to work around Webpack limitations. Webpack needs a way for packages to annotate extra files to include (this should not be a user config as the user shouldn't have to care). Please open a Webpack issue about that.

**Comment by fabiospampinato** [comment]
Understood, I'll just follow-up with the PR for removing `execa` from `term-size` then.

- WebPack issue related to supporting more dynamic imports: https://github.com/webpack/webpack/issues/9155
- WebPack issue related to requiring external files without bundling them in the main bundle: https://github.com/webpack/webpack/issues/9157

Thanks.
