### ISSUE TITLE
chown arguments are wrong

### ISSUE THREAD

**Issue by baleevskiy** [yeoman/update-notifier#168]
My users' group contains spaces and backslashes, that's why the following command won't work. 
![image](https://user-images.githubusercontent.com/13674755/62907546-22adef80-bdb7-11e9-9c8e-180beab0505f.png)

Potential fix: add quotes to the command
```bash
sudo chown -R "$USER":"$(id -gn $USER)" ./path
```

**Comment by sindresorhus** [comment]
Usernames and user group names are not meant to have spaces. I don't think we should do anything here. If you decide to go against the convention, it's up to you to handle the pitfalls.

https://unix.stackexchange.com/questions/401752/how-to-add-to-group-when-name-has-a-space
