### ISSUE TITLE
config-store dependency needs updating

### ISSUE THREAD

**Issue by zenlex** [yeoman/update-notifier#185]
per https://npmjs.com/advisories/1213  dot-prop versions prior to 5.1.1 have a prototype pollution vulnerability. It has been patched >=5.1.1. config-store has been updated to the newer dot-prop version.

**Comment by chayev** [comment]
Was this resolved? Or did you move this somewhere else? @zenlex

**Comment by zenlex** [comment]
So I could be wrong - I’m fairly new to the whole package management /npm ecosystem....this was brought up by a security vulnerability thrown by the gatsby-cli related to dot-prop, update-notifier, configurable-store. When I tried to trace the problem there was an issue filed on one of the other packages that said the dependency issue landed here so I made the issue. When I took another look at the package.json file here though it looked like the version had already been updated to the recommended spec.
