### ISSUE TITLE
How to get latest specific channel version

### ISSUE THREAD

**Issue by VerasThiago** [yeoman/update-notifier#194]
I was searching on the web and also on `update-notifier` documentation but unfortunately I haven't found anything about how to check for the latest update for a specific channel.

For example: I have a package that is on the `stable` version of `1.0.0`, but I released a `1.0.0-beta` and `2.0.0-beta` version. If I have an user that is using this package version at `1.0.0-beta`, how can I check for the latest beta version specifically ? Because I think this notifier will get me the latest version of the `stable` channel, no from `beta`.

If already this feature already exists, how to use it ?

**Comment by sindresorhus** [comment]
You want the [`distTag`](https://github.com/yeoman/update-notifier#disttag) option.

**Comment by VerasThiago** [comment]
Thank you! Problem solved
