### ISSUE TITLE
why do i have to optout by default?

### ISSUE THREAD

**Issue by adam-devel** [yeoman/update-notifier#205]
i don't remember being asked to opt in in the first place, and i do not want to bloat my .bashrc to disable things i did not ask for.
i want to be aware of what my computer is doing and to be able to control it; having random services running in the background unnecessarily make this hard.
this functionality is not really necessary for the program to work as expected, it's an option (hence the ability to opt-out)
this behavior should not be be the default one, instead users should take the decision of opting into additional fancy unrequired functionalities.

it's also easy to forget about the program, which make disabling it's behaviour consistently in multiple machines over time harder.
not to mention the privacy concerns

**Comment by sindresorhus** [comment]
Opt-out is just the default behavior for this package. Individual tools using `update-notifier` can choose to make it opt-in. Changing the default would be too much of a breaking change at this point, even if we wanted to. You should rather ask the tools you use to make it opt-in, not here.
