### ISSUE TITLE
`update-notifier` has 88 dependencies

### ISSUE THREAD

**Issue by fregante** [yeoman/update-notifier#211]
I wasn't expecting to see so many dependencies in for `update-notifier`: https://npmgraph.js.org/?q=update-notifier

Can they be reduced somehow? `boxen`, [`latest-version`](https://github.com/sindresorhus/latest-version/issues/19), and `configstore` seem to be the biggest offenders

**Comment by sindresorhus** [comment]
I'm sure some dependencies could be reduced, but I don't think you'll be able to massively reduce it while still handling all the edge-cases and the current functionality and look.

It's probably easier to propose specific actions, since just "reduce dependencies" is not very actionable.
