### ISSUE TITLE
Dependency update

### ISSUE THREAD

**Issue by opravil-jan** [yeoman/update-notifier#214]
Hi,

do you plan update boxen to latest version which fix vulnerability in old dependent packages.

Thanks
John

**Comment by constantinirimia** [comment]
Hi 
Are there any updates on this?

I have a dependency tree that is using update-notifier, but its child boxen is not getting updated so therefore the last node of the tree ansi-regex@4.1.0 is getting marked as high vulnerability!

Thank you
Constantin
