### ISSUE TITLE
Dependency update "boxen" 

### ISSUE THREAD

**Issue by tristangger** [yeoman/update-notifier#216]
The dependency "boxen" throws security warnings on vulnerability scans.
Can this be updated to Version 6.2.1 ?

**Comment by ItzRabbs** [comment]
Is there any intention of updating this dependency?

**Comment by Misenooooo** [comment]
I think it is getting a bit too long for this package to address a dependency update. There is even a proposal to replace this package completely in nodemon [thread](https://github.com/remy/nodemon/issues/1961).

**Comment by jimmywarting** [comment]
@Misenooooo #1961 is only focused on update-notifier and all of it's sub dependencies... `boxen` isn't part of update-notifier...
