### ISSUE TITLE
UpdateNotifierClass export missing since v6

### ISSUE THREAD

**Issue by jayree** [yeoman/update-notifier#226]
Is it possible to restore the v5 class export?

`module.exports.UpdateNotifier = UpdateNotifier;`

**Comment by sindresorhus** [comment]
That class is only an implementation detail. It was accidentally exposed before.

What do you need it for?

**Comment by jayree** [comment]
@sindresorhus I've used the class directly and enhanced some methods. E.g. support multiple distTags or add ChangeLog links.
