### ISSUE TITLE
Cannot use namespace 'ConfigStore' as a type. with version 5.1.0

### ISSUE THREAD

**Issue by xunzhaotech** [yeoman/update-notifier#227]
node_modules/.pnpm/@types+update-notifier@6.0.0/node_modules/@types/update-notifier/update-notifier.d.ts:7:22 - error TS2709: Cannot use namespace 'ConfigStore' as a type.
readonly config: ConfigStore;
                       ~~~~~~~~~~~


Found 1 error in node_modules/.pnpm/@types+update-notifier@6.0.0/node_modules/@types/update-notifier/update-notifier.d.ts:7

**Comment by sindresorhus** [comment]
`@types/update-notifier` is a different package. This package does not ship with type definitions.

Also: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
