### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by thaiat** [yeoman/update-notifier#47]
Hi,
I'm using codio as my editor (it's free and awesome by the way)
The box does not close well on the right as you can see here:
![codio_-_generator-angular-famous-ionic](https://cloud.githubusercontent.com/assets/4806944/4614572/828bf2d0-52e1-11e4-8ab8-b665f96842e7.png)

Outside of codio (using my laptop local command line) everything works fine:

![1__thaiat_avis-macbook-pro_____zsh_](https://cloud.githubusercontent.com/assets/4806944/4614575/86fa6e8c-52e1-11e4-802e-430192f955ff.png)

This is really non blocking, just for your info

**Comment by sindresorhus** [comment]
Not been able to reproduce this in a real terminal Probably something to do with them using a terminal emulator in the browser. PR welcome, but I doubt there's something we can do about it.
