### ISSUE TITLE
Crazypants idea: change notes

### ISSUE THREAD

**Issue by nevir** [yeoman/update-notifier#49]
If out of date, check for a `changelog.md` (or maybe `changelog.tldr.md`; configurable). Then print out all the goodies that the user is missing, 'cause we want to tempt them!

**Comment by kevva** [comment]
This is a bit much imo. Anyone else has any thoughts on this?

**Comment by arthurvr** [comment]
> This is a bit much imo. Anyone else has any thoughts on this?

Agreed
