### ISSUE TITLE
Respect `--no-update-notifier` flag?

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/update-notifier#50]
Currently this is handled by all dependents, but it might make it easier if we handle it.

We already handle the env var: https://github.com/yeoman/update-notifier/blob/7dbf2725f096198765fba7f89bdf1d43f1fba4b2/index.js#L47

Similar is done here: https://github.com/sindresorhus/supports-color/blob/e1815a472ebb59612e485096ae31a394e47d3c93/index.js#L5-L16

**Comment by henvic** [comment]
+1

Consider verifying if it's running on a CI (Travis, etc) also.

**Comment by henvic** [comment]
Just read this from the README.

> Users can also opt-out by setting the environment variable NO_UPDATE_NOTIFIER with any value.
> 
> You could also let the user opt-out on a per run basis:

```
if (process.argv.indexOf('--no-update-notifier') === -1) {
    // run updateNotifier()
}
```

This sounds good enough to me. On Travis, just add
```
env:
    - NO_UPDATE_NOTIFIER=true
```

See [List of CI environment variables used by Travis](http://docs.travis-ci.com/user/ci-environment/) if you're considering doing so using environment variables.

**Comment by sindresorhus** [comment]
Not nessecary to check if it's in a SCSI. It already doesn't run if stdout is not TTY.

**Comment by soulne4ny** [comment]
Environment name NO_UPDATE_NOTIFIER is horrible!
When one is checking environment, how does he or she can get an idea that NO_UPDATE_NOTIFIER relates to yeoman or npm?

**Comment by SBoudrias** [comment]
It relates to all packages depending on update-notifier. Not only yeoman
