### ISSUE TITLE
Option to make it more intrusive?

### ISSUE THREAD

**Issue by NickHeiner** [yeoman/update-notifier#51]
Hi! I recently had an amusing issue in which someone who uses my team's cli app didn't realize that updating was necessary to solve their problem. At first, they didn't even see the update notifier output. Then, after they saw it, it didn't occur to them that updating was important:

> It's just like all those annoying requests to update Flash or Java that don't actually impact my usage of those tools in any way. And the message didn't look ominous or like something that required immediate attention. 

To make this stand out to people more, I'm considering different options, like a giant ASCII-art pigeon, or the lyrics of Too Many Cooks printed out line-by-line with a sleep between each one. Would you have any interest in this? (It would be opt-in for consumers of this module, of course.) I could submit it as a PR, but it would also be easy to just implement it in my own project.

This is the pigeon I would use, in case it makes a difference:

```

     .-''-.
    / ,    \
 .-'`(o)    ;
'-==.       |
      `._...-;-.
      )--"""   `-.
     /   .        `-.
    /   /      `.    `-.
    |   \    ;   \      `-._________
    |    \    `.`.;          -------`.
     \    `-.   \\\\          `---...|
      `.     `-. ```\.--'._   `---...|
        `-.....7`-.))\     `-._`-.. /
          `._\ /   `-`         `-.,'
            / /
           /=(_
        -./--' `
      ,^-(_
      ,--' `
```

**Comment by mike-spainhower** [comment]
:+1: Perhaps cowsay could be another way to command better attention - https://github.com/piuccio/cowsay

**Comment by sindresorhus** [comment]
How would an ASCII figure help exactly? Wouldn't the user ignore that too? This sounds more like a user problem than something we should fix.

**Comment by kevva** [comment]
No thanks.

**Comment by arthurvr** [comment]
> No thanks.

+1 over here. Seems a little too much for me.

**Comment by NickHeiner** [comment]
Ok, I'm fine if people are not interested in this; I just thought I'd offer. For what it's worth, I implemented this as a wrapper, and thanks to the more obtrusive and humorous approach, my team no longer has problems where people are filing bugs that are fixed in the latest version that they haven't bothered to install yet. But it's definitely specific to my company's culture that this works, so I completely understand if this isn't appropriate for a broader audience.
