### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by step1step2** [yeoman/update-notifier#54]
http://i.imgur.com/H6FtjCE.png
Result:
0.6.6
undefined

**Comment by sindresorhus** [comment]
Please read: https://github.com/yeoman/update-notifier#how

It's graceful by default and check in the background and notifies on the next run, not the current. If it's the first time it's run it will wait the delay you've set until notifying as not to annoy people right away on the first run.

If you want feedback right away, use the callback as noted in the docs: https://github.com/yeoman/update-notifier#callbackerror-update

**Comment by sourcevault** [comment]
> 
> 
> http://i.imgur.com/H6FtjCE.png
> Result:
> 0.6.6
> undefined

image is no longer available.
