### ISSUE TITLE
Usage without callback never sets notifier.update

### ISSUE THREAD

**Issue by coderaiser** [yeoman/update-notifier#55]
Same behavior as in https://github.com/yeoman/update-notifier/issues/21
`iojs v2.3.0` and `node v0.12.4`
`update-notifier v0.5.0`

`update` field always `undefined`, notify box never shows up.

**Comment by sindresorhus** [comment]
Wait a day or manually modify the timestamp. It always skips the first timeout as not to bother the user on the first run.

**Comment by coderaiser** [comment]
Same result on second, third etc run.

**Comment by robbbz** [comment]
Seems like this should be re-opened.
