### ISSUE TITLE
Passing the content of package.json as a command line argument could cause problems

### ISSUE THREAD

**Issue by etiktin** [yeoman/update-notifier#57]
In the `check` method we pass the options object as a command line argument to check.js (see relevant line [here](https://github.com/yeoman/update-notifier/blob/0efdb3ea2e16693e1b15b9d57e69148fea3ebb1e/index.js#L64)). This means we pass the entire content of package.json as a command line argument (at least if the user followed the examples and didn't pass a custom `pkg` object). This is a potential problem, since certain platforms have a limit to the maximum length of the command line string (at least Windows does). So it can cause issues with really big package.json files. I think it would be better, if we update `options.pkg` (in the `UpdateNotifier` constructor) to contain just the relevant keys (name and version), so this will never become an issue.

**Comment by sindresorhus** [comment]
PR welcome
