### ISSUE TITLE
Humanize updatecheckinterval?

### ISSUE THREAD

**Issue by hemanth** [yeoman/update-notifier#59]
For [updatecheckinterval](https://github.com/yeoman/update-notifier#updatecheckinterval) options instead of `1000 * 60 * 60 * 24` we could say `1day` if it's humanized, would that be useful?

**Comment by sindresorhus** [comment]
I would agree if it were a commonly used option, but that option is only there for complete flexibility. The default should be good enough for most. Users can just use that kind of humanize lib directly in that case.

**Comment by hemanth** [comment]
:+1:
