### ISSUE TITLE
Update notifier throws "spawn E2BIG" error

### ISSUE THREAD

**Issue by Vortex** [yeoman/update-notifier#64]
I am getting "spawn E2BIG" error when I am trying to use the updater. I am on Ubuntu 15.10 (x64).

This is how the notifier is used:

var pkg = require('../package.json');
var updateNotifier = require('update-notifier');

var notifier = updateNotifier({
    pkg: pkg,
    updateCheckInterval: 1000 * 60 * 60 * 24 * 7 // 1 week 
});

notifier.notify();

**Comment by sindresorhus** [comment]
Already fixed in master: https://github.com/yeoman/update-notifier/commit/2ead0c954a081ed4039ba499e5f5a3ca6708fbd7

I'm working on doing a new release.
