### ISSUE TITLE
Heaviness

### ISSUE THREAD

**Issue by natew** [yeoman/update-notifier#65]
Want to use this for a cli, but it's already gotten heavy and this adds on quite a bit to install time.

Looking into it, latest-version => package-json => got => (10 dependencies)

So if we could avoid package-json this package would be lean and mean, as it should be.

**Comment by sindresorhus** [comment]
Then don't use it. It's using those dependencies for a reason. HTTP is hard. It started out smaller, then reality kicked. Lots of edge-cases to cover. Most other things use `request` which is a lot bigger, so in the big picture, `got` is small. I really doubt it has much effect on your install time. Dependencies are cached, so only uncached ones are downloaded.

If we just avoided all dependencies it would be even smaller. Of course then it wouldn't work :p

Happy to receive specific suggestions for improvements, but we can't just remove dependencies we depend.

**Comment by natew** [comment]
@sindresorhus thanks for the response. This one was helpful. I'm just using `npm view` to get the latest version, which I guess probably has downsides compared to this.

My only intention was to open a dialogue because I ran into a real problem. I'm on a brand new iMac with a core i7 4.0 processor and it took ~6 seconds to install this package, thus the issue.

This seems relatively simple: https://github.com/feross/simple-get but of course I don't know if it covers all your use cases.

(see how nice of a conversation is possible if you treat people like people?)

**Comment by sindresorhus** [comment]
> This seems relatively simple: https://github.com/feross/simple-get but of course I don't know if it covers all your use cases.

I'm aware of it, but it misses a lot of important things.

It would also not really help:

```
~/Downloads
❯ time npm install got
got@5.1.0 node_modules/got
├── lowercase-keys@1.0.0
├── is-stream@1.0.1
├── timed-out@2.0.0
├── is-redirect@1.0.0
├── object-assign@4.0.1
├── unzip-response@1.0.0
├── is-plain-obj@1.1.0
├── node-status-codes@1.0.0
├── create-error-class@2.0.1 (capture-stack-trace@1.0.0, inherits@2.0.1)
├── parse-json@2.2.0 (error-ex@1.3.0)
├── pinkie-promise@1.0.0 (pinkie@1.0.0)
├── url-parse-lax@1.0.0 (prepend-http@1.0.3)
├── read-all-stream@3.0.1 (readable-stream@2.0.4)
└── duplexify@3.4.2 (readable-stream@2.0.4, end-of-stream@1.0.0)

real	5.33s
user	1.33s
sys	0.34s
                                                                                                                                               
~/Downloads
❯ time npm install simple-get
simple-get@1.4.3 node_modules/simple-get
├── unzip-response@1.0.0
├── xtend@4.0.1
└── once@1.3.2 (wrappy@1.0.1)

real	4.60s
user	0.71s
sys	0.11s
```

----

got@6, which we're currently working on, is estimated to be around 100kb when finished. That's half the size of `simple-get`.

> (see how nice of a conversation is possible if you treat people like people?)

That goes both ways.

-

The main problem here is that npm is super slow, not the size of the dependencies. 1 MB is nothing today. See: https://github.com/npm/npm/issues/10380

**Comment by natew** [comment]
@sindresorhus honest question, did I do something offensive? I realize the title of this could perhaps come off as short, but it wasn't meant that way.

Shrugging and closing an issue is a pretty negative move to make. But it's a tiny thing, and I'm over it. I was opening these issues in good spirit.
