### ISSUE TITLE
publish new release

### ISSUE THREAD

**Issue by abhishekisnot** [yeoman/update-notifier#66]
Thank you very much for this package. One little pbm: Updating the dep versions [here](https://github.com/yeoman/update-notifier/commit/7ef4438806d5acaa8f95734486aed19ce285c6d5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R39) fixes 401 (Unauthorized) for private scoped packages. But latest version 0.5.0 on npm is not updated with fixes. Can we please publish latest version?

**Comment by SBoudrias** [comment]
Done. 0.6.0
