### ISSUE TITLE
Update configstore dependency

### ISSUE THREAD

**Issue by nikeee** [yeoman/update-notifier#72]
The current used version uses `configstore ^1.0.0` wich depends on `graceful-fs`<4. `graceful-fs`<4 is deprecated as it uses node APIs that will soon be unavailable.
The update-notifier should upgrade to `configstore ^2.0.0` to avoid incompability with newer node versions, if possible.

**Comment by SBoudrias** [comment]
PR welcomed.

**Comment by sindresorhus** [comment]
This request is invalid. There was no dependency bump in `configstore` between v1.4.0 and v2.0.0, and `configstore` 1.4.0 matches `^1.0.0`.

**Comment by nikeee** [comment]
Actually you're right. It was tsd referencing an old version of update-notifier referencing an old version of configstore referencing graceful-fs<=3.
