### ISSUE TITLE
How to confirm it's working?

### ISSUE THREAD

**Issue by callumlocke** [yeoman/update-notifier#74]
I'm using update-notifier on [ESBox](https://github.com/callumlocke/esbox).

I added update-notifier to esbox@0.5, and now esbox@0.6 is out. So I thought I'd test if update-notifier is working by doing `npm install -g esbox@0.5` then running it. I've run `esbox --help` several times (including waiting a few hours in between runs) but I never get the update notification. I've also tried deleting `~/.config/configstore/update-notifier-esbox.json` and I can see the file gets re-created when I run `esbox --help` again. But on subsequent runs, it still never shows the message.

Am I doing something wrong?

**Comment by sindresorhus** [comment]
It will by default only notify maximum once a day. Try deleting `~/.config/configstore/update-notifier-esbox.json` and run it twice and on the second time it should appear.

**Comment by callumlocke** [comment]
I've tried that lots of times.

```
# delete the config file
rm ~/.config/configstore/update-notifier-esbox.json
# (also manually verified it's gone)

# install esbox v0.5.0
> npm uninstall -g esbox
> npm install -g esbox@0.5.0

# run esbox once
> esbox --version
0.5.0

# verify the config got re-created
cat ~/.config/configstore/update-notifier-esbox.json
{
  "optOut": false,
  "lastUpdateCheck": 1458666066820
}

# wait a few minutes...

# run esbox again
esbox --version
0.5.0

# no update notification :(

# check the config again, unchanged
cat ~/.config/configstore/update-notifier-esbox.json
{
  "optOut": false,
  "lastUpdateCheck": 1458666066820
}
```

Here is the line of code in esbox v0.5.0 where update notifier runs: https://github.com/callumlocke/esbox/blob/v0.5.0/src/lib/cli.js#L18

And from the fact the config file gets created, it looks like it works, but I just never see the notification.

**Comment by callumlocke** [comment]
ooh could it be because I do `process.exit(0);`? would that stop the notification showing at the end?

I just thought of that because I saw this issue on loud-rejection earlier today :) https://github.com/sindresorhus/loud-rejection/issues/13

**Comment by sindresorhus** [comment]
> ooh could it be because I do process.exit(0);? would that stop the notification showing at the end?

No: https://github.com/yeoman/update-notifier/blob/4896088fe3c03e69ad462e9b27c67abc94e9e8e7/index.js#L97

-

Oh right. Now I remember. You need to change `"lastUpdateCheck"` to `"lastUpdateCheck": 0` to force it to report. The reason it doesn't now is that it always wait a day until it's first notification, so to not be annoying to the user. I should document this better.

**Comment by callumlocke** [comment]
I tried that too. Tried 0 and also tried changing it to a month ago.

**Comment by callumlocke** [comment]
Sorry, just tried that again and it worked! Thanks

I think the reason it didn't work last time is, instead of testing with `esbox -v`, I was actually running it properly, and esbox is a CLI that generally runs until you quit it with ctrl+C. I'm guessing the problem was that update notifier doesn't show if you quit in that way? In which case, is that a bug or expected?

**Comment by sindresorhus** [comment]
> In which case, is that a bug or expected?

Just not expected. `process.on('exit')` is not called for `SIGINT` (Ctrl+C). Not really sure if it makes sense. Need to think about it.

// @SBoudrias @eddiemonge Opinions?

**Comment by SBoudrias** [comment]
@sindresorhus I don't think Node will allow to schedule async tasks while trying to close the process.

**Comment by sindresorhus** [comment]
@SBoudrias The `.notify()` method is not async. My question was whether it makes sense to show the update notification on `SIGINT`? Right now it's only shown on normal process exit.

**Comment by SBoudrias** [comment]
Ah got it. I think it'll be fine to show on SIGINT.
