### ISSUE TITLE
Allow update message to be customized via notify(opts) method

### ISSUE THREAD

**Issue by nexdrew** [yeoman/update-notifier#77]
A similar idea in #43 was dismissed as "useless", but now that the `.notify()` method is non-trivial, why not allow things like message parts, chalk styles, and boxen settings to be customized via opts? This would make the `.notify()` method more consumer-friendly and reusable.

Consider that if someone wants to provide the same functionality but with a slight customization, they currently have to duplicate/reproduce the following:

- is-npm dependency
- boxen dependency
- chalk dependency
- check for `!process.stdout.isTTY || isNpm || !notifier.update`
- message parts/concatenation
- chalk styles
- boxen settings/style
- check for deferral and process exit listener

That's kind of a lot.

I think it would be nice to support the following:

- `opts.updateCommand`: string like `'sudo npm i %s -g --ignore-scripts'`
- `opts.boxenOptions`: object passed directly to boxen

But we could get even more granular than that:

- `opts.updateAvailableMessage`: string like `'Update available %s → %s'`
- `opts.runMessage`: string like `'Run %s to update'`
- `opts.currentVersionStyle`: string like `'dim'` or function like `chalk.dim`
- `opts.latestVersionStyle`: string like `'green'` or function like `chalk.green`
- `opts.updateCommandStyle`: string like `'cyan'` or function like `chalk.cyan`
- `opts.padding`: integer passed to boxen
- `opts.margin `: integer passed to boxen
- `opts.borderColor `: string passed to boxen
- `opts.borderStyle `: string passed to boxen

A bonus for supporting message/text customization is that folks can then support i18n if they want, but still get the benefit of the other logic.

Thoughts?

**Comment by sindresorhus** [comment]
👍 Good point. We should definitely allow passing in a custom message. When it comes to customizing the default one, I'm open to it, but I don't want [too many options](https://cloud.githubusercontent.com/assets/170270/15021714/9073a69a-1252-11e6-9810-2b58317a1be8.png).

**Comment by matheuss** [comment]
I think that should be implemented ASAP 😅 

``` js
var pkg = require('./package.json'),
    updateNotifier = require('update-notifier');
    
updateNotifier({pkg: pkg}).notify(); 
```

<img width="682" alt="screen shot 2016-05-10 at 1 03 35 am" src="https://cloud.githubusercontent.com/assets/4721750/15135309/0bbddfa4-164b-11e6-9bb1-cc7fdcb577a6.png">

It would be *very* cool to have an easy way (too many options is definitely not something cool) to customize the message. I'll try to implement something here and I'll send a PR as soon as i get something good 😊
