### ISSUE TITLE
Don't count deprecated versions as new versions

### ISSUE THREAD

**Issue by LinusU** [yeoman/update-notifier#78]
We are using update-notifier internally to force everyone to be on the latest version of a command line tool. Today someone pushed a broken build, and then promptly `npm deprecated` it.

It would be nice if deprecated versions simply didn't count as a new version.

**Comment by sindresorhus** [comment]
The correct way would have been to also change the dist tag to the previous version? That way you wouldn't get the deprecated version when doing `npm install module` and it would *just* work here.

**Comment by LinusU** [comment]
That's cool! Running the following command solved it, `my-pkg` is the name of the module, `0.13.2` was the last version that worked.

```sh
npm dist-tag add my-pkg@0.13.2 latest
```

Thanks
