### ISSUE TITLE
notify() options in README.md has typos

### ISSUE THREAD

**Issue by uglow** [yeoman/update-notifier#91]
I know this is small, but it cost me a few minutes to figure out and is easy to change...

In `readme.md`:
- [ ] rename the `notify()` method's `options.name` property to `options.packageName`
- [ ] rename the `notify()` method's `options.version` property to `options.packageVersion`
- [ ] Clarify that if `pkg` is passed, it will ignore try to use `pkg.name` and `pkg.version`(if they exist) instead of the above properties

FWIW, I came across this issue while developing [generator-confit](https://github.com/odecee/generator-confit), which uses semantic versioning, so the version in `package.json` was set to `0.0.0-semantically-released`. I needed to read the source code to see what was going on. 

Great package btw! 👍

**Comment by sindresorhus** [comment]
>  rename the notify() method's options.name property to options.packageName
 rename the notify() method's options.version property to options.packageVersion

No, the current is correct. https://github.com/yeoman/update-notifier/commit/b97b8cbc123462ac952cad80660a6b6a8645a1ac Look at the readme again. The `name` and `version` is part of the `pkg` option.

**Comment by uglow** [comment]
Right - I see. In my case I just need to create an object called `pkg` with those two properties, rather than setting `pkg` to the package.json object. 

Thanks @sindresorhus

**Comment by sindresorhus** [comment]
You can do either.
