### ISSUE TITLE
Any interest in looking at GitHub version?

### ISSUE THREAD

**Issue by mhkeller** [yeoman/update-notifier#95]
I made a fork of this with two new options: looking at GitHub tag version instead of npm and setting a custom install string while keeping the rest of the install message design. 

You can see the changes here https://github.com/yeoman/update-notifier/compare/master...mhkeller:master

The install string option is different from the current custom install message in that it keeps the design the same except for the specific `npm install <org>/<pkg-name>` default install string. This is useful for adding environment variables or other specifics that preface `npm install`.

I was going to publish it as a new modules but if there is any interest to incorporate it, I can make a pull request.

**Comment by sindresorhus** [comment]
Make a new module. This one is focused on the 95% use-case, which is npm.
