### ISSUE TITLE
Not displaying update notification (updateNotifier.notify())

### ISSUE THREAD

**Issue by mikeerickson** [yeoman/update-notifier#99]
I am testing with my CLI and no matter what settings I use, the `notify()` routine never fires (or does not display anything)

```
const updateNotifier = require('update-notifier');
const pkg = require('./package.json');

updateNotifier({pkg, callback: function (err, update) {
  console.log('update', update.latest);
}}).notify();
```

I have also done the simple

```
updateNotifier({pkg}).notify();
```

The local version I am testing has v1.2.0, while the version on npm is v1.2.3, thus making me feel the update notification should be displayed.

**Comment by mikeerickson** [comment]
I have the following object returned by updateNotifier

```
const notifier = updateNotifier({pkg});
console.log(JSON.stringify(notifier));
```
returns

```
{"options":{"pkg":{"name":"package-menu-cli","version":"1.2.3"}},"packageName":"package-menu-cli","packageVersion":"1.2.3","updateCheckInterval":86400000,"hasCallback":false,"config":{"path":"/Use
rs/mikeerickson/.config/configstore/update-notifier-package-menu-cli.json"}}
```

I am reading the `How` instructions and it intimates that it will make two calls, second of which is a package which contains the `update` property?

**Comment by roccomuso** [comment]
Having the callback supposes to have a single version check, right? without having to wait the `updateCheckInterval`

**Comment by sindresorhus** [comment]
I've expanded on the `How` section a bit to clarify things: https://github.com/yeoman/update-notifier#how Note the second paragraph.
